CREATE TABLE [dbo].[tblPokemon]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [SpeciesId] UNIQUEIDENTIFIER NOT NULL,
    [AbilityId] UNIQUEIDENTIFIER NOT NULL,
    [NatureId] UNIQUEIDENTIFIER NOT NULL,
    [Type1Id] UNIQUEIDENTIFIER NOT NULL,
    [Type2Id] UNIQUEIDENTIFIER NOT NULL,
    [ItemId] UNIQUEIDENTIFIER NULL, 
    [MajorStatus] UNIQUEIDENTIFIER NULL,
    [IsShiny] BIT NOT NULL,
    [Nickname] varchar(50) NULL,
    [Level] INT NOT NULL, 
    [CurrentHP] int NOT NULL,
    [HPIVs] INT NOT NULL, 
    [AttackIVs] INT NOT NULL, 
    [DefenseIVs] INT NOT NULL, 
    [SpecialAttackIVs] INT NOT NULL, 
    [SpecialDefenseIVs] INT NOT NULL, 
    [SpeedIVs] INT NOT NULL, 
    [HPEVs] INT NOT NULL, 
    [AttackEVs] INT NOT NULL, 
    [DefenseEVs] INT NOT NULL, 
    [SpecialAttackEVs] INT NOT NULL, 
    [SpecialDefenseEVs] INT NOT NULL, 
    [SpeedEVs] INT NOT NULL, 
)
